version: 2

models:
  - name: link_contact_account
    description: Link table containing relationship between Contact and Account entities
    columns:
      - name: contact_account_hk
        description: Primary key of the table
      - name: contact_hk
        description: Foreign key referencing hub
        tests:
          - relationships:
              to: ref('hub_contact')
              field: contact_hk
      - name: account_hk
        description: Foreign key referencing hub
        tests:
          - relationships:
              to: ref('hub_account')
              field: account_hk
      - name: load_datetime
        description: Standard metadata column according to DV standards
      - name: record_source
        description: Standard metadata column according to DV standards

  - name: link_opportunity_account
    description: Link table containing relationship between Opportunity and Account entities
    columns:
      - name: opportunity_account_hk
        description: Primary key of the table
      - name: opportunity_hk
        description: Foreign key referencing hub
        tests:
          - relationships:
              to: ref('hub_opportunity')
              field: opportunity_hk
      - name: account_hk
        description: Foreign key referencing hub
        tests:
          - relationships:
              to: ref('hub_account')
              field: account_hk
      - name: load_datetime
        description: Standard metadata column according to DV standards
      - name: record_source
        description: Standard metadata column according to DV standards

  - name: link_lead_contact
    description: Link table containing relationship between Lead and Contact entities
    columns:
      - name: lead_contact_hk
        description: Primary key of the table
      - name: lead_hk
        description: Foreign key referencing hub
        tests:
          - relationships:
              to: ref('hub_lead')
              field: opportunity_hk
      - name: contact_hk
        description: Foreign key referencing hub
        tests:
          - relationships:
              to: ref('hub_contact')
              field: contact_hk
      - name: load_datetime
        description: Standard metadata column according to DV standards
      - name: record_source
        description: Standard metadata column according to DV standards